# Sprint 14

## Keras

### [Problem 1] Sharing and executing the official tutorial model

In [1]:
import tensorflow as tf

In [2]:
# Load the data
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
# Example model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
# Logits from the first sample
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.39897233, -0.05583327, -0.73508793, -0.6665918 ,  0.04693446,
         0.7848796 , -0.46473372, -0.59100634,  0.24258548, -0.6889942 ]],
      dtype=float32)

In [5]:
# Convert logits to probabilities
tf.nn.softmax(predictions).numpy()

array([[0.15479058, 0.09822566, 0.04979989, 0.05333053, 0.10885701,
        0.22768894, 0.0652592 , 0.0575178 , 0.13238128, 0.05214908]],
      dtype=float32)

In [6]:
# Objective function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
# Configurate and compile the model
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3012 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1449 - accuracy: 0.9571: 0s - loss: 0.1470 - ac
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1095 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0879 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0758 - accuracy: 0.9755


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0724 - accuracy: 0.9770


[0.07243641465902328, 0.9769999980926514]

In [10]:
# Return probabilities right away
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.53524193e-09, 1.38714782e-07, 6.01757438e-06, 1.34830843e-04,
        7.15464701e-11, 3.83733209e-07, 8.69825655e-14, 9.99856949e-01,
        4.37243102e-07, 1.13263286e-06],
       [1.02295623e-07, 1.03874605e-04, 9.99884605e-01, 1.04464352e-05,
        1.46658419e-14, 3.98723841e-07, 4.93291111e-07, 1.95466364e-12,
        1.09474570e-07, 2.75311132e-13],
       [1.54051378e-07, 9.99355733e-01, 7.08013613e-05, 4.44623993e-06,
        1.29973059e-05, 8.08008372e-06, 5.44347176e-06, 3.64070293e-04,
        1.77123889e-04, 1.17052082e-06],
       [9.96882915e-01, 7.06612937e-08, 2.78900698e-04, 3.84474606e-06,
        2.92759232e-05, 2.66143470e-05, 1.58052688e-04, 2.57594977e-03,
        1.04552146e-06, 4.34298054e-05],
       [1.17624040e-07, 2.45754617e-09, 1.39660560e-05, 9.84404210e-07,
        9.88049924e-01, 1.06889092e-06, 1.98317352e-07, 1.44484176e-04,
        2.76109040e-06, 1.17864357e-02]], dtype=float32)>

### [Problem 2] (Advance assignment) Execute various methods

I will try to execute in another workspace.

### [Problem 3] Learning Iris (binary classification) with Keras

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [13]:
#Load dataset
df = pd.read_csv("../Sprint 13/Iris.csv")

#Condition extraction from data frame
df = df[(df["Species"] == "Iris-versicolor") | (df["Species"] == "Iris-virginica")]
y = df["Species"]
X = df.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]

# NumPy
X = np.array(X)
y = np.array(y)

# Convert label to number
y[y == "Iris-versicolor"] = 0
y[y == "Iris-virginica"] = 1
y = y.astype(np.int64)[:, np.newaxis]

scaler = StandardScaler()
scaler.fit_transform(X)

#Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

In [14]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation="relu", input_shape=(4,)),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

In [15]:
model.compile(optimizer='adam',
              loss="binary_crossentropy",
              metrics=['accuracy'])

In [16]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 50)                250       
_________________________________________________________________
dense_3 (Dense)              (None, 100)               5100      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 101       
Total params: 5,451
Trainable params: 5,451
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_val, y_val), batch_size=10)

Epoch 1/100
7/7 [==============================] - 0s 22ms/step - loss: 0.7047 - accuracy: 0.4688 - val_loss: 0.7312 - val_accuracy: 0.3750
Epoch 2/100
7/7 [==============================] - 0s 5ms/step - loss: 0.6724 - accuracy: 0.5312 - val_loss: 0.7141 - val_accuracy: 0.3750
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6617 - accuracy: 0.5312 - val_loss: 0.6659 - val_accuracy: 0.3750
Epoch 4/100
7/7 [==============================] - 0s 5ms/step - loss: 0.6436 - accuracy: 0.7344 - val_loss: 0.6622 - val_accuracy: 0.3750
Epoch 5/100
7/7 [==============================] - 0s 5ms/step - loss: 0.6256 - accuracy: 0.5469 - val_loss: 0.6771 - val_accuracy: 0.3750
Epoch 6/100
7/7 [==============================] - 0s 5ms/step - loss: 0.6232 - accuracy: 0.5312 - val_loss: 0.6687 - val_accuracy: 0.3750
Epoch 7/100
7/7 [==============================] - 0s 5ms/step - loss: 0.6155 - accuracy: 0.6875 - val_loss: 0.6126 - val_accuracy: 0.9375
Epoch 8/100
7/7 [=========

7/7 [==============================] - 0s 5ms/step - loss: 0.1512 - accuracy: 0.9688 - val_loss: 0.1159 - val_accuracy: 1.0000
Epoch 60/100
7/7 [==============================] - 0s 4ms/step - loss: 0.1437 - accuracy: 0.9688 - val_loss: 0.1198 - val_accuracy: 1.0000
Epoch 61/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1477 - accuracy: 0.9688 - val_loss: 0.1123 - val_accuracy: 1.0000
Epoch 62/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1431 - accuracy: 0.9531 - val_loss: 0.1098 - val_accuracy: 1.0000
Epoch 63/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1372 - accuracy: 0.9844 - val_loss: 0.1097 - val_accuracy: 1.0000
Epoch 64/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1391 - accuracy: 0.9688 - val_loss: 0.1036 - val_accuracy: 1.0000
Epoch 65/100
7/7 [==============================] - 0s 5ms/step - loss: 0.1389 - accuracy: 0.9531 - val_loss: 0.1013 - val_accuracy: 1.0000
Epoch 66/100
7/7 [===============

In [18]:
model.evaluate(X_test,  y_test, verbose=2)

1/1 - 0s - loss: 0.1940 - accuracy: 0.9500


[0.19401291012763977, 0.949999988079071]

### [Problem 4] Learn Iris (multi-level classification) with Keras

In [19]:
df = pd.read_csv("../Sprint 13/Iris.csv")

y = df["Species"].values
X = df.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]].values

encoder = OneHotEncoder()
y_one_hot = encoder.fit_transform(y[:, np.newaxis]).toarray()

#Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=0)

# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

In [20]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation="relu", input_shape=(4,)),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(3, activation="softmax")
])

In [21]:
model.compile(optimizer='adam',
              loss="categorical_crossentropy",
              metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 50)                250       
_________________________________________________________________
dense_6 (Dense)              (None, 100)               5100      
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 303       
Total params: 5,653
Trainable params: 5,653
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_val, y_val), batch_size=10)

Epoch 1/100
10/10 [==============================] - 0s 12ms/step - loss: 1.1659 - accuracy: 0.3021 - val_loss: 1.0339 - val_accuracy: 0.3750
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 1.0018 - accuracy: 0.3854 - val_loss: 0.9087 - val_accuracy: 0.6250
Epoch 3/100
10/10 [==============================] - 0s 2ms/step - loss: 0.8845 - accuracy: 0.6667 - val_loss: 0.8134 - val_accuracy: 0.7083
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.7843 - accuracy: 0.6875 - val_loss: 0.7298 - val_accuracy: 0.7083
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: 0.7018 - accuracy: 0.6875 - val_loss: 0.6559 - val_accuracy: 0.7083
Epoch 6/100
10/10 [==============================] - 0s 2ms/step - loss: 0.6286 - accuracy: 0.6875 - val_loss: 0.5932 - val_accuracy: 0.7083
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5682 - accuracy: 0.6875 - val_loss: 0.5429 - val_accuracy: 0.7083
Epoch 8/100


Epoch 59/100
10/10 [==============================] - 0s 6ms/step - loss: 0.0724 - accuracy: 0.9792 - val_loss: 0.2160 - val_accuracy: 0.9167
Epoch 60/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0766 - accuracy: 0.9688 - val_loss: 0.1954 - val_accuracy: 0.9167
Epoch 61/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0845 - accuracy: 0.9583 - val_loss: 0.1819 - val_accuracy: 0.9167
Epoch 62/100
10/10 [==============================] - 0s 3ms/step - loss: 0.0627 - accuracy: 0.9688 - val_loss: 0.2090 - val_accuracy: 0.9167
Epoch 63/100
10/10 [==============================] - 0s 4ms/step - loss: 0.0571 - accuracy: 0.9896 - val_loss: 0.1714 - val_accuracy: 0.9167
Epoch 64/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0658 - accuracy: 0.9792 - val_loss: 0.2313 - val_accuracy: 0.9167
Epoch 65/100
10/10 [==============================] - 0s 5ms/step - loss: 0.0662 - accuracy: 0.9688 - val_loss: 0.1839 - val_accuracy: 0.9167
Epoch 

In [24]:
model.evaluate(X_test, y_test, verbose=2)

1/1 - 0s - loss: 0.0262 - accuracy: 1.0000


[0.026219788938760757, 1.0]

### [Problem 5] Learning House Prices with Keras

In [25]:
df = pd.read_csv('../Week 5/train.csv')

y = df[['SalePrice']].values
X = df[['GrLivArea', 'YearBuilt']].values

X = (X - X.mean()) / X.std()
y = (y - y.mean()) / y.std()

#Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# さらにtrainとvalに分割
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

In [26]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation="relu", input_shape=(2,)),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, activation="relu"),
])

In [27]:
model.compile(optimizer='adam',
              loss="mse",
              metrics=['mse'])

In [28]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 50)                150       
_________________________________________________________________
dense_9 (Dense)              (None, 100)               5100      
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 101       
Total params: 5,351
Trainable params: 5,351
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_val, y_val), batch_size=10)

Epoch 1/100
94/94 [==============================] - 0s 2ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 2/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 3/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 4/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 5/100
94/94 [==============================] - 0s 1000us/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 6/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 7/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 8/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 

94/94 [==============================] - 0s 968us/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 63/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 64/100
94/94 [==============================] - 0s 985us/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 65/100
94/94 [==============================] - 0s 984us/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 66/100
94/94 [==============================] - 0s 980us/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 67/100
94/94 [==============================] - 0s 996us/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 68/100
94/94 [==============================] - 0s 1ms/step - loss: 1.0024 - mse: 1.0024 - val_loss: 0.8718 - val_mse: 0.8718
Epoch 69/100
94/94 [==============================] - 0s 986us/step - loss: 1.0

In [30]:
model.evaluate(X_test, y_test, verbose=2)

10/10 - 0s - loss: 1.0950 - mse: 1.0950


[1.095018744468689, 1.095018744468689]

### [Problem 6] Learning MNIST with Keras

In [31]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(-1, 784)
X_test = X_test.reshape(-1, 784)
X_train = X_train.astype(np.float)
X_test = X_test.astype(np.float)
X_train /= 255
X_test /= 255

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2)

print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)

enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train = enc.fit_transform(y_train[:, np.newaxis])
y_val = enc.transform(y_val[:, np.newaxis])
y_test = enc.transform(y_test[:, np.newaxis])

print(y_train.shape)
print(y_val.shape)

(48000, 784)
(48000,)
(12000, 784)
(12000,)
(48000, 10)
(12000, 10)


In [32]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation="relu", input_shape=(784,)),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(10, activation="softmax"),
])

In [33]:
model.compile(optimizer='adam',
              loss="categorical_crossentropy",
              metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 50)                39250     
_________________________________________________________________
dense_12 (Dense)             (None, 100)               5100      
_________________________________________________________________
dense_13 (Dense)             (None, 10)                1010      
Total params: 45,360
Trainable params: 45,360
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(X_train, y_train, epochs=20, validation_data=(X_val, y_val), batch_size=100)

Epoch 1/20
480/480 [==============================] - 1s 2ms/step - loss: 0.3995 - accuracy: 0.8866 - val_loss: 0.2132 - val_accuracy: 0.9368
Epoch 2/20
480/480 [==============================] - 1s 2ms/step - loss: 0.1683 - accuracy: 0.9504 - val_loss: 0.1627 - val_accuracy: 0.9528
Epoch 3/20
480/480 [==============================] - 1s 2ms/step - loss: 0.1247 - accuracy: 0.9627 - val_loss: 0.1310 - val_accuracy: 0.9610
Epoch 4/20
480/480 [==============================] - 1s 2ms/step - loss: 0.1004 - accuracy: 0.9695 - val_loss: 0.1205 - val_accuracy: 0.9649
Epoch 5/20
480/480 [==============================] - 1s 2ms/step - loss: 0.0815 - accuracy: 0.9752 - val_loss: 0.1113 - val_accuracy: 0.9682
Epoch 6/20
480/480 [==============================] - 1s 2ms/step - loss: 0.0692 - accuracy: 0.9796 - val_loss: 0.1100 - val_accuracy: 0.9689
Epoch 7/20
480/480 [==============================] - 1s 2ms/step - loss: 0.0596 - accuracy: 0.9818 - val_loss: 0.1045 - val_accuracy: 0.9696
Epoch 

In [36]:
model.evaluate(X_test, y_test, verbose=2)

313/313 - 0s - loss: 0.1149 - accuracy: 0.9742


[0.11492910236120224, 0.9742000102996826]

In [38]:
model(X_test[:1]).numpy()

array([[6.9977695e-14, 5.4889209e-12, 4.2814513e-08, 1.1383728e-05,
        6.8971312e-17, 1.7613234e-10, 2.4817042e-18, 9.9998856e-01,
        5.5416876e-08, 7.8254399e-09]], dtype=float32)