In [2]:
import numpy as np
from sklearn.preprocessing import Binarizer, KBinsDiscretizer

In [19]:
X = np.arange(0,8).reshape(8,1)

In [20]:
Binarizer(threshold=3).fit_transform(X)

array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [22]:
KBinsDiscretizer(n_bins=5).fit_transform(X).toarray()

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [23]:
7/5

1.4

In [38]:
from sklearn.impute import *

In [39]:
X = np.array([
    [1,5],
    [10,np.nan],
    [np.nan,1]
])

In [40]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit_transform(X)

array([[ 1. ,  5. ],
       [10. ,  3. ],
       [ 5.5,  1. ]])

In [45]:
X = np.array([
    [6,7],
    [9,1],
    [14,0],
    [np.nan, 7]
])

In [47]:
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[ 6. ,  7. ],
       [ 9. ,  1. ],
       [14. ,  0. ],
       [ 7.5,  7. ]])

Pipeline Advanced

In [48]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_selector, make_column_transformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.impute import SimpleImputer
import seaborn as sns

In [49]:
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [51]:
y = titanic['survived']
X = titanic.drop('survived', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [53]:
numerical_features = ['pclass', 'age', 'fare']
categorical_features = ['sex', 'deck', 'alone']

In [66]:
numerical_pipeline = make_pipeline(SimpleImputer(strategy='mean'), StandardScaler())
categorical_pipeline = make_pipeline(SimpleImputer(strategy='most_frequent'), OneHotEncoder())

In [67]:
preprocessor = make_column_transformer((numerical_pipeline, numerical_features),
                                     (categorical_pipeline, categorical_features))

In [68]:
model = make_pipeline(preprocessor, SGDClassifier())

model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [65]:
#make_column_selector()
numerical_features = make_column_selector(dtype_include=np.number)
categorical_features = make_column_selector(dtype_exclude=np.number)