# Mathematics for Machine Learning
## Assignment 3 - Matrix Scratch

**[Problem 1] Matrix product is calculated manually**

If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix,
$$\displaystyle \mathbf {A} ={\begin{pmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{pmatrix}},\quad \mathbf {B} ={\begin{pmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{pmatrix}}$$

the matrix product $C = AB$ (denoted without multiplication signs or dots) is defined to be the $m \times p$ matrix
$$\displaystyle \mathbf {C} ={\begin{pmatrix}c_{11}&c_{12}&\cdots &c_{1p}\\c_{21}&c_{22}&\cdots &c_{2p}\\\vdots &\vdots &\ddots &\vdots \\c_{m1}&c_{m2}&\cdots &c_{mp}\\\end{pmatrix}}$$

such that
$${\displaystyle c_{ij}=a_{i1}b_{1j}+a_{i2}b_{2j}+\cdots +a_{in}b_{nj}=\sum _{k=1}^{n}a_{ik}b_{kj},}$$
for $i = 1, ..., m$ and $j = 1, ..., p$.

Therefore, with
$$A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]$$

We will have C is an 3x3 matrix with:

$ C_{11} = -1 \times 0 + 2 \times 0 + 3 \times 2 = 6 $

$ C_{12} = -1 \times 2 + 2 \times 2 + 3 \times 9 = 29 $

$ C_{13} = -1 \times 1 + 2 \times -8 + 3 \times -1 = -20$

$ C_{21} = 4 \times 0 + -5 \times 0 + 6 \times 2 = 12 $

$ C_{22} = 4 \times 2 + -5 \times 2 + 6 \times 9 = 52 $

$ C_{23} = 4 \times 1 + -5 \times -8 + 6 \times -1 = 38 $

$ C_{31} = 7 \times 0 + 8 \times 0 + -9 \times 2 = -18 $

$ C_{32} = 7 \times 2 + 8 \times 2 + -9 \times 9 = -51 $

$ C_{33} = 7 \times 1 + 8 \times -8 + -9 \times -1 = -48 $

The result matrix is:
$$C = \left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]$$

**[Problem 2] Calculation by NumPy function**

In [1]:
import numpy as np
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(A @ B)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [2]:
#Testing np.matmul()
print(np.matmul(A, B))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
#Testing np.dot()
print(np.dot(A, B))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**[Problem 3] Implementation of calculation of a certain element**

In [4]:
ele_0_0 = 0
for k in range(0,3):
    ele_0_0 += A[0][k] * B[k][0]
print(ele_0_0)

6


In [5]:
def matrix_mul(a, b):
    c = np.array([])
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c_ij = 0
            for k in range(a.shape[1]):
                c_ij += a[i][k] * b[k][j]
            c = np.append(c, c_ij)
    c = c.reshape(a.shape[0], b.shape[1])
    return c

In [6]:
C = matrix_mul(A, B)
print(C)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [7]:
#Test with another matrix
At = np.array([[1, 0, 5, -3], [3, 2, 7, -2]])
Bt = np.array([[0, 6], [4, 2], [3, 5], [10, -4]])
print(At.shape)
print(Bt.shape)
Ct = matrix_mul(At, Bt)
print(Ct)

(2, 4)
(4, 2)
[[-15.  43.]
 [  9.  65.]]


**[Problem 5] Judge the input whose calculation is not defined**

In [8]:
def matrix_mul_with_checker(a, b):
    #Check if the number of columns of a != the number of rows of b
    if a.shape[1] != b.shape[0]:
        raise Exception("The matrix product can't be done. Please check the dimension!")
    c = np.array([])
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c_ij = 0
            for k in range(a.shape[1]):
                c_ij += a[i][k] * b[k][j]
            c = np.append(c, c_ij)
    c = c.reshape(a.shape[0], b.shape[1])
    return c

In [9]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
f_ndarray = matrix_mul_with_checker(d_ndarray_, e_ndarray)

Exception: The matrix product can't be done. Please check the dimension!

**[Problem 6] Transposition**

In [ ]:
#Transpose the matrix D
d_ndarray = d_ndarray_.T

#Check the shape of 2 arrays
print(d_ndarray.shape, e_ndarray.shape)

f_ndarray = matrix_mul_with_checker(d_ndarray, e_ndarray)
print(f_ndarray)